// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBPZOJYS-1InnsmgDlyeo_gJ6jmM2PiKw',
    appId: '1:451734690659:web:3fd4a66153497c00f29156',
    messagingSenderId: '451734690659',
    projectId: 'mindful-minutes-a0c03',
    authDomain: 'mindful-minutes-a0c03.firebaseapp.com',
    storageBucket: 'mindful-minutes-a0c03.firebasestorage.app',
    measurementId: 'G-6RE8RDKDZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2iJ51amxpImKm02KZ5JvniG9qqooMm-Q',
    appId: '1:451734690659:android:16a76caddff79e0ff29156',
    messagingSenderId: '451734690659',
    projectId: 'mindful-minutes-a0c03',
    storageBucket: 'mindful-minutes-a0c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_TUxYNCj7APmndXt1iDy3349ld_EI48M',
    appId: '1:451734690659:ios:5eb9f7773c07c63bf29156',
    messagingSenderId: '451734690659',
    projectId: 'mindful-minutes-a0c03',
    storageBucket: 'mindful-minutes-a0c03.firebasestorage.app',
    androidClientId: '451734690659-3dj27dr9mi9t1rkb0l6690qsh2gmn24h.apps.googleusercontent.com',
    iosClientId: '451734690659-un6pntjhv6135u4fm6mna12d19raanfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBigapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_TUxYNCj7APmndXt1iDy3349ld_EI48M',
    appId: '1:451734690659:ios:e08066b754ee43f0f29156',
    messagingSenderId: '451734690659',
    projectId: 'mindful-minutes-a0c03',
    storageBucket: 'mindful-minutes-a0c03.firebasestorage.app',
    androidClientId: '451734690659-3dj27dr9mi9t1rkb0l6690qsh2gmn24h.apps.googleusercontent.com',
    iosClientId: '451734690659-pj3j84bj5b0nmre6fhf5au3v43jp5nrv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBigapp.RunnerTests',
  );
}
